### ISSUE TITLE
"for _ in range(2)" in function getFrame cause real fps is half of configed RefreshRate.

### ISSUE THREAD

**Issue by hustlong** [adafruit/Adafruit_CircuitPython_MLX90640#35]
i dont understand  "for _ in range(2)"

**Comment by tekktrik** [comment]
The sensor uses two subpages to collect data, alternating between them at the given **subpage** refresh rate.  In order to collect the full image, both subpages are collected.  The `for` loop handles this process of grabbing the two subpages to create one single frame.  See [Section 10.4 of the datasheet](https://www.melexis.com/-/media/files/documents/datasheets/mlx90640-datasheet-melexis.pdf).  That means in order to achieve a given **frame** refresh rate, you'll need to use double the **subpage** refresh rate.
